bitsandbytes/config/routes.rb
Rails.application.routes.draw do
  resources :boards do
  resources :entries
end

  devise_for :users
  root 'boards#index'
end
  

bitsandbytes/app/models/board.rb
class Board < ActiveRecord::Base
  belongs_to :user
  has_many :entries
end

bitsandbytes/app/models/entry.rb
class Entry < ActiveRecord::Base
  belongs_to :board
end

bitsandbytes/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :boards
end

bitsandbytes/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

bitsandbytes/app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: [:show, :edit, :update, :destroy]

  # GET /boards
  # GET /boards.json
  def index
    @boards = Board.all
  end

  # GET /boards/1
  # GET /boards/1.json
  def show
    @entries = @board.entries
    # raise
  end

  # GET /boards/new
  def new
    @board = Board.new
  end

  # GET /boards/1/edit
  def edit
  end

  # POST /boards
  # POST /boards.json
  def create
    @board = Board.new(board_params)

    respond_to do |format|
      if @board.save
        format.html { redirect_to @board, notice: 'Board was successfully created.' }
        format.json { render :show, status: :created, location: @board }
      else
        format.html { render :new }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boards/1
  # PATCH/PUT /boards/1.json
  def update
    respond_to do |format|
      if @board.update(board_params)
        format.html { redirect_to @board, notice: 'Board was successfully updated.' }
        format.json { render :show, status: :ok, location: @board }
      else
        format.html { render :edit }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boards/1
  # DELETE /boards/1.json
  def destroy
    @board.destroy
    respond_to do |format|
      format.html { redirect_to boards_url, notice: 'Board was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_board
      @board = Board.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def board_params
      params.require(:board).permit(:name, :user_id)
    end
end

bitsandbytes/app/controllers/entries_controller.rb
class EntriesController < ApplicationController
	def index
    @entries= Entry.all
  end

  def new
    @entries = Entry.new
    @board = Board.find(params[:board_id])
  end

  def create
    @entry = Entry.new
    @entry.board_id = params["entry"]["board_id"]
    @entry.upvote = params["entry"]["upvote"]
    @entry.url = params["entry"]["url"]
    @entry.note = params["entry"]["note"]
    @entry.save
    redirect_to '/boards/'
  end

  def upvote
    @entry = Resource.find(params[:id])
    @vote = @entry.upvote + 1
    @entry.upvote = @vote
    @entry.save
    redirect_to '/boards/'
  end

  def edit
  end

  def update
  end

  def destroy
    @entry = Entry.find(params[:id])
    @entry.destroy
    redirect_to '/boards/'
  end
end  
  private
  def entries_params
    params.require(:url).permit(:user_id, :notes, :upvotes, :board_id)
  end

bitsandbytes/app/helpers/application_helper.rb
module ApplicationHelper
end

bitsandbytes/app/helpers/boards_helper.rb
module BoardsHelper
end

bitsandbytes/app/helpers/entries_helper.rb
module EntriesHelper
end

bitsandbytes/app/views/boards/_form.html.erb
<%= form_for(@board) do |f| %>
  <% if @board.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@board.errors.count, "error") %> prohibited this board from being saved:</h2>

      <ul>
      <% @board.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.hidden_field :user_id, value: current_user.id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

bitsandbytes/app/views/boards/edit.html.erb
<h1>Editing Board</h1>

<%= render 'form' %>

<%= link_to 'Show', @board %> |
<%= link_to 'Back', boards_path %>

bitsandbytes/app/views/boards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Boards</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @boards.each do |board| %>
      <tr>
        <td><%= board.name %></td>
        <td><%= board.user.email %></td>
        <td><%= link_to 'Show', board %></td>
        <td><%= link_to 'Edit', edit_board_path(board) %></td>
        <td><%= link_to 'Destroy', board, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Board', new_board_path %>

bitsandbytes/app/views/boards/new.html.erb
<h1>New Board</h1>

<%= render 'form' %>

<%= link_to 'Back', boards_path %>

bitsandbytes/app/views/boards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @board.name %>
</p>

<p>
  <strong>User:</strong>
  <%= @board.user.email %>
</p>

<% @entries.each do |entry| %>
  <h3><%= link_to entry.url, entry.url %></h3>
  <p><%= entry.note %></p>
  <p><%= entry.upvote %></p>
  <%= button_to('Destroy', board_entry_path, :method => 'delete', :class => 'btn btn-large btn-primary')  %>
<% end %>

<%= link_to 'Create a New Entry', new_board_entry_path(@board) %><br>
<%= link_to 'Edit', edit_board_path(@board) %> |
<%= link_to 'Back', boards_path %>

bitsandbytes/app/views/entries/_form.html.erb
<%= form_for @entries do |f|%>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.hidden_field :upvote, value: 1 %>
  <%= f.label :URL %><br>
  <%= f.text_field :url %><br>
  <%= f.label :note %><br>
  <%= f.text_field :note %><br>
  <%= f.submit "New Entry", :class => 'btn btn-primary btn-sm' %>
<% end %>

bitsandbytes/app/views/entries/new.html.erb
<%= form_for([@board, @entries]) do |f| %>
  <div class="field">
    <%= f.label :URL %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :note %><br>
    <%= f.text_area :note %>
  </div>
  <div>
  <%= f.hidden_field :board_id, value: @board.id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

bitsandbytes/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bitsandbytes</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>